### ISSUE TITLE
Allow for default values in expansion syntax

### ISSUE THREAD

**Issue by autodidaddict** [sagiegurari/envmnt#19]
**Features Description**
The exposure I have to this crate leads me to believe that either the default syntax isn't documented, or it doesn't support default values. 

**Describe the solution you'd like**
Today, I can expand things like `${MY_VAR}`, but I would like to be able to supply defaults, e.g. `${MY_VAR:default_value}` so that if the environment variable isn't present, it uses a default value that's supplied within the text being expanded.

**Comment by sagiegurari** [comment]
that's interesting idea.
i currently have it only support platform type expansions:
https://sagiegurari.github.io/envmnt/api/envmnt/types/enum.ExpansionType.html

i could add some custom type with default value support.
but only in the format you suggested, meaning wrapped with ${}

**Comment by autodidaddict** [comment]
Even if it only worked on Unix type expansiona, it would be incredibly
useful for other projects in and around the cloud.

**Comment by sagiegurari** [comment]
Cool. i'm on it

**Comment by autodidaddict** [comment]
Awesome thanks!

**Comment by sagiegurari** [comment]
0.8.2 version is now released.
you will need to set the expansion type to the new UnixBracketsWithDefaults

https://sagiegurari.github.io/envmnt/api/envmnt/types/enum.ExpansionType.html#variant.UnixBracketsWithDefaults

Thanks a lot for the idea.
