### ISSUE TITLE
Flatten and impl std::error::Error for EnvmntError

### ISSUE THREAD

**Issue by lweberk** [sagiegurari/envmnt#28]
### Feature Description
Have `EnvmntError` be more docile when matching or chaining against it from downstream. For chaining implementing `std::error::Error` is necessary.

### Describe The Solution You'd Like
Move ErrorKind member into EnvmntError, making the latter an enumeration. Implement `std::error::Error` for it.

### Side Effects
Reduction of code for anything depending on matching against `EnvmntError.kind`.

**Comment by sagiegurari** [comment]
PR?

**Comment by lweberk** [comment]
Should I do it against `0.8.5` branch?

**Comment by sagiegurari** [comment]
ya, I'll probably bump it to 0.9 as its a breaking change

**Comment by sagiegurari** [comment]
This is now released in 0.9 version
