### ISSUE TITLE
Environment expansion working differently in 0.10.0 and 0.10.2

### ISSUE THREAD

**Issue by bakjos** [sagiegurari/envmnt#35]
### Describe The Bug
In the version 0.10.0 if I use ` ${ADDRESS:http://127.0.0.1:1234}` and the env variable is not defined it was returning `http://127.0.0.1:1234` in the version 0.10.2 this doesn't work and it returns the same `${ADDRESS:http://127.0.0.1:1234}`

**Comment by sagiegurari** [comment]
I'll check it out

**Comment by bakjos** [comment]
> I'll check it out

Thank you

**Comment by sagiegurari** [comment]
@bakjos sorry for the late reply. this is now fixed and released.
